name: ci
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Copy .env
        run: cp .env.example .env
      - name: Run docker-composer
        run: docker-compose up -d
