name: lint
on:
  push:
    branches:
      - master
    paths:
      - '**.py'

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: tonybajan/flake8-check-action@v1.0.0
      with:
        select: E,F,B,G0
        maxlinelength: 100
        repotoken: ${{ secrets.GITHUB_TOKEN }}
