name: lint
on:
  push:
    branches:
      - master
    paths:
      - '**.py'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: tonybajan/flake8-check-action@v1.0.0
      with:
        maxlinelength: 80
        repotoken: ${{ secrets.GITHUB_TOKEN }}
