name: test
on: push

jobs:
  run-tests:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set Up Python 3.8.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.8.6
      - name: Install dependencies
        run: pip install -r requirements.py
      - name: Run Tests
        run: python manege.py test apps
