name: test
on: push

jobs:
  run-tests:
    name: Run linters
    runs-on: ubuntu-latest

    services:
      image: postgres:9.6.18
      env:
        - POSTGRES_USER: postgres
        - POSTGRES_PASSWORD: postgres
        - POSTGRES_DB: postgres
        - PGDATA: /var/lib/postgresql/data/pgdata
      ports:
        - 5432:5432

    steps:
      - uses: actions/checkout@v1
      - name: Set Up Python 3.8.5
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8.5
      - name: Install dependencies
        run: pip install -r requirements.py
      - name: Run Tests
        run: python manege.py test apps
